<?php namespace DirectoryCrawler\Scrapers;

Class Entries extends Scraper
  {
    protected $model;
    protected $regex;
    protected $targetLink;

    public function invoke()
    {
        return parent::invoke(); // TODO: Change the autogenerated stub
    }
}
?>
