<?php namespace DirectoryCrawler\Scrapers;

Class Entry extends BaseScraper
  {
     protected $htmlDom;
     protected $selector;
     protected $parameter;
     protected $target_link;
     
     protected $model;
     
     public function invoke()
     {
         return parent::invoke(); // TODO: Change the autogenerated stub
     }
}
?>
