<?php
    set_time_limit(0);
require_once __DIR__ . '/../vendor/autoload.php';
// Crawler
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\CssSelector\CssSelectorConverter;
// Controller
use DirectoryCrawler\Controllers\DomCrawlerController;
use DirectoryCrawler\Controllers\B99CrawlerController;

// Model
use DirectoryCrawler\Models\CrawlerLink;
use DirectoryCrawler\Models\Category;
use DirectoryCrawler\Models\Locations;
use DirectoryCrawler\Models\Entry;

// Scraper
use DirectoryCrawler\Scrapers\Categories;

// Filters
use DirectoryCrawler\Helpers\Filter;
if (empty($_SESSION)) {
    session_start();
}
$crawlData = $_SESSION['crawlData'];

$crawler = $crawlData['crawler'];
$cat = $crawlData['cat'];

$current_record = $_GET['current_record'];
$record_count = $crawler->saveSecondTierLinks($current_record);

//$_SESSION['crawlData']['total_records'] = $record_count;
$response = array(
    'message' => 'Total Records: ' . $_SESSION['crawlData']['total_records'] .'<br/>' .
                'Processing records in batches, current record: ' . $current_record . '<br/>Entries generated by this batch: ' . $record_count. '<br/>' .
                'Total entries generated: ' . $_SESSION['current_records_created'],
    'deeper_level_exists' => true
);
?>
<html>
<head>
</head>
<body><?php echo $response['message'] ;?>
<?php
if ($record_count==0) {
?>
    <script>
        var stuburl = "mining.php?current_record=0";
        window.location = stuburl;
    </script>
<?php
} else {
$current_record+=10;
?>
    <script>
        var stuburl = "entries-stub.php?current_record=<?php echo $current_record; ?>";
        window.location = stuburl;
    </script>
    <?php
}?>

</body>
</html>